---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: quant-factor-monthly
spec:
  schedule: "00 00 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: quant-ingestion-production
            image: quant-ingestion
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - main.py --backtest_period 12 --weeks_to_expire 4 --sample_interval 4 --average_days 7 --processes 30 --recalc_ratio --recalc_premium
            - main.py --backtest_period 12 --weeks_to_expire 8 --sample_interval 4 --average_days 7 --processes 30 --recalc_ratio
            - main.py --backtest_period 12 --weeks_to_expire 13 --sample_interval 4 --average_days 7 --processes 30 --recalc_ratio
            - main.py --backtest_period 12 --weeks_to_expire 26 --sample_interval 4 --average_days 7 --processes 30 --recalc_ratio
            resources:
              # TODO: update requirements
              requests:
                memory: "8Mi"
                cpu: "30000m"
              limits:
                memory: "32Mi"
                cpu: "30000m"
          restartPolicy: Never
