#TODO: separate skaffold for separate components(?)

apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: quant-factors

profiles:
- name: quant-factors-microk8s
  activation:
  - kubeContext: microk8s-factors
  - kubeContext: minikube           # LATER MOVE
  build:
    artifacts:
       - image: utils
         context: utils
         docker:
           dockerfile: .Dockerfile
       - image: factor
         requires:
           - image: utils
             alias: BASE
         docker:
           dockerfile: components/base.Dockerfile
#      - image: factor-base
#        context: ../
#        docker:
#          dockerfile: components/base.Dockerfile
#      - image: factor-data-preparation
##        context: ../
#        requires:
#          - image: factor-base
#            alias: BASE
#        docker:
#          dockerfile: components/data_preparation/Dockerfile
#      - image: factor-model-training
#          #        context: ../
#          requires:
#              - image: factor-base
#                alias: BASE
#          docker:
#            dockerfile: components/model_training/Dockerfile
#      - image: factor-model-evaluation
#          #        context: ../
#          requires:
#              - image: factor-base
#                alias: BASE
#          docker:
#            dockerfile: components/model_evaluation/Dockerfile
  deploy:
    kubectl:
      manifests:
        - k8s.yaml