apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: quant-factors

profiles:
- name: quant-factors-microk8s
  activation:
  - kubeContext: microk8s-factors
  - kubeContext: minikube           # LATER MOVE
  build:
    artifacts:
      - image: factor-base
#        context: ../
        docker:
          dockerfile: components/base.Dockerfile
      - image: factor-data-preparation
#        context: ../
        requires:
          - image: factor-base
            alias: BASE
        docker:
          dockerfile: components/data_preparation/Dockerfile
  deploy:
    kubectl:
      manifests:
        - k8s.yaml
