# TODO: Is it better to have separate k8s file for each components or 1 aggregate one?

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: quant-[Job Name]
spec:
  schedule: "00 00 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: quant-[Container Name]
            image: quant-[Image Name]
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - ...   # Need to customize according to each repo (separate data / training / prediction)
            resources:
              requests:
                memory: "12Gi"
                cpu: "12000m"
              limits:
                memory: "24Gi"
                cpu: "24000m"
          restartPolicy: Never
