---
apiVersion: batch/v1
kind: Job
metadata:
  name: quant-factors-temp
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: quant-factors
        image: factor
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - python3 components/data_preparation/main.py --weeks_to_expire 8 --recalc_ratio --recalc_premium --recalc_subpillar --processes 12
        - python3 components/data_preparation/main.py --weeks_to_expire 4 --recalc_premium --recalc_subpillar --processes 12
        - python3 components/data_preparation/main.py --weeks_to_expire 26 --recalc_premium --recalc_subpillar --processes 12
        - python3 components/model_training/main.py --weeks_to_expire 8 --backtest_period 21 --processes 12
        - python3 components/model_training/main.py --weeks_to_expire 4 --backtest_period 21 --processes 12
        - python3 components/model_training/main.py --weeks_to_expire 26 --backtest_period 21 --processes 12
        - python3 components/model_evaluation/main.py --weeks_to_expire 8 --eval_factor --eval_top --eval_select --processes 12
        - python3 components/model_evaluation/main.py --weeks_to_expire 4 --eval_factor --eval_top --eval_select --processes 12
        - python3 components/model_evaluation/main.py --weeks_to_expire 26 --eval_factor --eval_top --eval_select --processes 12
        resources:
          requests:
            memory: "12Gi"
            cpu: "12000m"
          limits:
            memory: "24Gi"
            cpu: "24000m"
      restartPolicy: Never

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: quant-factors-weekly
spec:
  schedule: "00 00 * * 0"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: quant-factors
            image: factor
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - python3 components/data_preparation/main.py --weeks_to_expire 8 --recalc_ratio --recalc_premium --recalc_subpillar --processes 12
            - python3 components/data_preparation/main.py --weeks_to_expire 4 --recalc_premium --recalc_subpillar --processes 12
            - python3 components/data_preparation/main.py --weeks_to_expire 26 --recalc_premium --recalc_subpillar --processes 12
            - python3 components/model_training/main.py --weeks_to_expire 8 --backtest_period 21 --processes 12
            - python3 components/model_training/main.py --weeks_to_expire 4 --backtest_period 21 --processes 12
            - python3 components/model_training/main.py --weeks_to_expire 26 --backtest_period 21 --processes 12
            - python3 components/model_evaluation/main.py --weeks_to_expire 8 --eval_factor --eval_top --eval_select --processes 12
            - python3 components/model_evaluation/main.py --weeks_to_expire 4 --eval_factor --eval_top --eval_select --processes 12
            - python3 components/model_evaluation/main.py --weeks_to_expire 26 --eval_factor --eval_top --eval_select --processes 12
            resources:
              requests:
                memory: "12Gi"
                cpu: "12000m"
              limits:
                memory: "24Gi"
                cpu: "24000m"
          restartPolicy: Never