---
apiVersion: batch/v1
kind: Job
metadata:
  name: debug-run
  namespace: quant-factors
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: quant-factors
        image: quant-factor
        imagePullPolicy: IfNotPresent
        command: [
              "/bin/sh",
              "-c",
              " python3 components/model_training/main.py --weeks_to_expire 8 --backtest_period 21 --processes 12 --currency_code USD  --debug --end_date 2022-10-17           &&
              python3 components/model_evaluation/main.py --weeks_to_expire 8 --eval_factor --eval_top --eval_select --processes 12  --debug  
        "]
        resources:
          limits:
            memory: "30Gi"
            cpu: "12000m"
      restartPolicy: Never
