---
apiVersion: batch/v1
kind: Job
metadata:
  name: quant-factors-preprocess-history
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: quant-factors
        image: quant-factor
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - python3 components/data_preparation/main.py --weeks_to_expire 8 --recalc_ratio --recalc_premium --recalc_subpillar --processes 12 --history
        - python3 components/data_preparation/main.py --weeks_to_expire 4 --recalc_premium --recalc_subpillar --processes 12 --history
        - python3 components/data_preparation/main.py --weeks_to_expire 26 --recalc_premium --recalc_subpillar --processes 12 --history
        resources:
          requests:
            memory: "12Gi"
            cpu: "12000m"
          limits:
            memory: "24Gi"
            cpu: "24000m"