# TODO: if we should seprate skaffold.yaml for components?

apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: quant-[Repo Short Name]
build:
  artifacts:
    - image: quant-[Image Name]
      context: .
      docker:
        dockerfile: ./Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s.yaml

profiles:

  - name: quant-[Repo Short Name]-minikube
    activation:
      - kubeContext: minikube
    deploy:
      kubectl:
        manifests:
          - k8s_minikube.yaml
        hooks:
          after:
            - host:
                command:
                  [
                    "echo",
                    "Skaffold Profile: quant-[Repo Short Name]-minikube"
                  ]

  - name: quant-[Repo Short Name]-microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      kubectl:
        manifests:
          - k8s.yaml
        hooks:
          after:
            - host:
                command:
                  [
                    "echo",
                    "Skaffold Profile: quant-[Repo Short Name]-microk8s"
                  ]