apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  POSTGRES_USERNAME: "postgres"
  POSTGRES_DB: "postgres"
  POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
  POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
  PGDATA: "/var/lib/postgresql/data/pgdata"
