---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  volumeName: postgresql-pv
  resources:
    requests:
      storage: "4Gi"
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
